{{- $fullName := include "daemonset.fullname" . -}}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "daemonset.fullname" . }}
  labels:
    {{- include "daemonset.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "daemonset.selectorLabels" . | nindent 6 }}
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "daemonset.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "daemonset.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- if .Values.initContainers.enabled }}
      initContainers:
        {{- range .Values.initContainers.containers }}
        - name: {{ .name }}
          image: {{ .image }}
          {{- if .command }}
          command: {{ .command | toJson }}
          {{- end }}
          {{- if .args }}
          args: {{ .args | toJson }}
          {{- end }}
          {{- if .env }}
          env:
            {{- toYaml .env | nindent 12 }}
          {{- end }}
          {{- if .volumeMounts }}
          volumeMounts:
            {{- toYaml .volumeMounts | nindent 12 }}
          {{- end }}
        {{- end }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if or .Values.env .Values.configmap.enabled .Values.ExternalSecret.enabled }}
          {{- if .Values.env }}
          env:
            {{- toYaml .Values.env | nindent 12 }}
          {{- end }}
          envFrom:
          {{- if .Values.configmap.enabled }}
          - configMapRef:
              name: {{ include "daemonset.fullname" . }}
          {{- end }}
          {{- if .Values.ExternalSecret.enabled }}
          - secretRef:
              name: {{ include "daemonset.fullname" . }}
          {{- end }}
          {{- end }}
          {{- if .Values.configmap.enabled }}
          {{- if .Values.configmap.fileData }}
          volumeMounts:
          {{- range .Values.configmap.fileData }}
          - name: custom-config-volume-{{ .fileName | replace ".yaml" "" | replace ".yml" "" | replace ".json" "" | replace ".conf" "" }}
            mountPath: {{ .mountPath }}/{{ .fileName }}
            subPath: {{ .fileName }}
          {{- end }}
          {{- end }}
          {{- end }}
          ports:
            {{- range .Values.service.ports }}
            - name: {{ .name }}
              containerPort: {{ .targetPort }}
              protocol: {{ .protocol }}
            {{- end }}
          {{- with .Values.postStart }}
          lifecycle:
            postStart:
              {{- toYaml . | nindent 14 }}
          {{- end }}
          {{- include "daemonset.probe" (dict "probe" .Values.probes.startup "probeType" "startup") | nindent 10 }}
          {{- include "daemonset.probe" (dict "probe" .Values.probes.liveness "probeType" "liveness") | nindent 10 }}
          {{- include "daemonset.probe" (dict "probe" .Values.probes.readiness "probeType" "readiness") | nindent 10 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- if .Values.configmap.enabled }}
      {{- if .Values.configmap.fileData }}
      volumes:
      {{- range .Values.configmap.fileData }}
      - name: custom-config-volume-{{ .fileName | replace ".yaml" "" | replace ".yml" "" | replace ".json" "" | replace ".conf" "" }}
        configMap:
          name: {{ $fullName }}
          items:
          - key: {{ .fileName }}
            path: {{ .fileName }}
      {{- end }}
      {{- end }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
