{{- if and .Values.ExternalSecret.enabled (eq .Values.ExternalSecret.type "hashicorp") }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "deployment.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: {{ .Values.ExternalSecret.name }}
    kind: SecretStore
  target:
    name: {{ include "deployment.fullname" . }}
    creationPolicy: Owner
    deletionPolicy: Retain
  dataFrom:
{{- range .Values.ExternalSecret.kvPath }}
    - extract:
        key: {{ . }}
        metadataPolicy: None
        decodingStrategy: None
        conversionStrategy: Default
{{- end }}
{{- end }}